### ISSUE TITLE
Money transfer

### ISSUE THREAD

**Issue by jardiacaj** [jardiacaj/finem_imperii#6]
There is currently no way to transfer money between characters.

Open questions:

- Effects of distance on money transfers (proposals: introduce a fee to transfer money to a different location; alternatively allow transfer to local characters only).
- Instant or turn-based?
- How to avoid giving an advantage to users having multiple accounts? (maybe not so important yet)

**Comment by StegSchreck** [comment]
first idea reading this issue:
* instant money transfer if both characters are in the same location
* implicitly "hire a mounted messenger" for transferring money over distance
  * you have to pay for his service ("fee")
  * takes a certain amount of time per distance unit to deliver the money (turn-based)

additional thought on implementing a messenger: 
* can he be robbed? (by other players? by the system?)

Suggestion: incremental implementation
1. only local, instant money transfer
2. transfer money over distance by hiring a messenger (costing money and time)
3. messenger can betray you (in X% of the cases) and transfer fails
4. different types of messengers (different amount of reliability with different kinds of fees)
5. messenger can be robbed by others (same possibility as the reliability of the messenger?)

**Comment by StegSchreck** [comment]
Basic money transfer is implemented (bulletpoint 1 from my List)
@jardiacaj, shall we leave like this for now as this ticket is marked minor?
Or do you see the transfer over distance as required?

**Comment by jardiacaj** [comment]
Thanks! Once I reviewed and merged it I would simply remove it from the milestone and leave the issue open.

**Comment by jardiacaj** [comment]
Merged, review in 9b5e32931c60d20cac027bfb831c409c528f77db.

Also added message to receiving character in 3792626f1285cc61a51dbcbf9838cc60dd856fc4 and c5ad89a4a5a141611a7d691d40d4ccb541286ff0.
